name: Ordering Deployment

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20' # Adjust to your preferred Node.js version

      - name: Install Dependencies
        run: yarn

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Build React Application
      - name: Build React Application
        run: yarn build

      # Deploy static site to S3 bucket
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://ordering-0.2 --delete
